### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by yoniji** [flurry/upload-clients#8]
Hi,

We had acquired token base on  [this article](https://developer.yahoo.com/flurry/docs/api/code/apptoken/). 

The script returns error:
```
Showing Recent Issues
14:04:36 [INFO] upload-symbols.py:85	fetching project

14:04:40 [INFO] upload-symbols.py:88	taring files

14:04:44 [INFO] upload-symbols.py:95	archive: /var/folders/z1/nyq0fd3d6c176tqzlrfs2hth0000gn/T/tmp02Z6x_.tgz (4314919 b)

14:04:44 [INFO] upload-symbols.py:97	creating upload

14:04:45 [INFO] upload-symbols.py:100	uploading file

error uploading file. <urlopen error [Errno 32] Broken pipe> <class 'urllib2.URLError'>
```

Thanks!

**Comment by clayreimann** [comment]
Thanks for the report @yoniji, can you run the script adding the argument `--log DEBUG`

**Comment by yoniji** [comment]
Hi @clayreimann ,
Thanks for your reply. The output is as follow:
```
11:58:08 [DEBUG] upload-symbols.py:475	--------------------
11:58:08 [DEBUG] upload-symbols.py:476	apiKey=TSRDS4XFRRY229W6ZXV7
11:58:08 [DEBUG] upload-symbols.py:477	search_path=/Users/northcity/Library/Developer/Xcode/DerivedData/magicruler-dgfgvnavyezexwbqgwpvmxxuosxm/Build/Products/Debug-iphoneos
11:58:08 [DEBUG] upload-symbols.py:478	wait=True
11:58:08 [DEBUG] upload-symbols.py:479	max_wait=600
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
ValueError: unsupported format character 'b' (0x62) at index 12
Logged from file upload-symbols.py, line 480
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
ValueError: unsupported format character 'b' (0x62) at index 17
Logged from file upload-symbols.py, line 481
11:58:08 [DEBUG] upload-symbols.py:482	--------------------
11:58:08 [INFO] upload-symbols.py:85	fetching project
11:58:13 [DEBUG] upload-symbols.py:189	project: {u'data': [{u'type': u'project', u'id': u'796526'}]}
11:58:13 [INFO] upload-symbols.py:88	taring files
11:58:13 [DEBUG] upload-symbols.py:209	looking for dsyms in /Users/northcity/Library/Developer/Xcode/DerivedData/magicruler-dgfgvnavyezexwbqgwpvmxxuosxm/Build/Products/Debug-iphoneos
11:58:13 [DEBUG] upload-symbols.py:219	Adding magicruler.app.dSYM to tar
11:58:16 [INFO] upload-symbols.py:95	archive: /var/folders/z1/nyq0fd3d6c176tqzlrfs2hth0000gn/T/tmprdxqbq.tgz (4329362 b)
11:58:16 [INFO] upload-symbols.py:97	creating upload
11:58:18 [DEBUG] upload-symbols.py:278	Created upload {u'data': {u'relationships': {u'project': {u'data': {u'type': u'project', u'id': u'796526'}}}, u'attributes': {u'uploadType': u'IOS', u'contentLength': 4329362, u'modifiedDate': 1483934297954, u'creationDate': 1483934297954, u'uploadStatus': u'CREATED', u'failureReason': None}, u'type': u'upload', u'id': u'23197'}}
11:58:18 [INFO] upload-symbols.py:100	uploading file

```

**Comment by clayreimann** [comment]
@yoniji We've deployed some tweaks to our backend, could you try sending your symbols again?

**Comment by yoniji** [comment]
Hi @clayreimann
Thanks a lot!
We've resent the symbols and got a new error:

```
Showing Recent Issues
10:57:39 [DEBUG] upload-symbols.py:482	--------------------


10:57:39 [INFO] upload-symbols.py:85	fetching project


10:57:43 [DEBUG] upload-symbols.py:189	project: {u'data': [{u'type': u'project', u'id': u'796526'}]}


10:57:43 [INFO] upload-symbols.py:88	taring files


10:57:43 [DEBUG] upload-symbols.py:209	looking for dsyms in /Users/northcity/Library/Developer/Xcode/DerivedData/magicruler-dgfgvnavyezexwbqgwpvmxxuosxm/Build/Products/Debug-iphoneos


10:57:43 [DEBUG] upload-symbols.py:219	Adding magicruler.app.dSYM to tar


10:57:46 [INFO] upload-symbols.py:95	archive: /var/folders/z1/nyq0fd3d6c176tqzlrfs2hth0000gn/T/tmpyU775j.tgz (4343784 b)


10:57:46 [INFO] upload-symbols.py:97	creating upload


10:57:49 [DEBUG] upload-symbols.py:278	Created upload {u'data': {u'relationships': {u'project': {u'data': {u'type': u'project', u'id': u'796526'}}}, u'attributes': {u'uploadType': u'IOS', u'contentLength': 4343784, u'modifiedDate': 1484189864768, u'creationDate': 1484189864768, u'uploadStatus': u'CREATED', u'failureReason': None}, u'type': u'upload', u'id': u'24117'}}


10:57:49 [INFO] upload-symbols.py:100	uploading file


error uploading file. '' <class 'httplib.BadStatusLine'>



```
